/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hasmartcomsimulator;

import hasmart.*;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        PLCController.register("");
    }
}
